### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by a308086178** [nanchengxi/jjdouzeroAuto#1]
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

====== RESTART: C:\Users\戴华乾\Documents\jjdouzeroAuto-main\Auto_JJ2\main.py =====
pygame 2.5.2 (SDL 2.28.3, Python 3.10.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
[WARNING 2024-03-03 10:11:22,693 _assert_and_prepare_model_files:102] can not find model file C:\Users\戴华乾\AppData\Roaming\cnocr\2.2\ppocr\en_PP-OCRv3_rec_infer.onnx 
Traceback (most recent call last):
  File "C:\Users\戴华乾\Documents\jjdouzeroAuto-main\Auto_JJ2\main.py", line 32, in <module>
    ocr = CnOcr(det_model_name='en_PP-OCRv3_det', rec_model_name='en_PP-OCRv3',
  File "C:\Users\戴华乾\AppData\Local\Programs\Python\Python310\lib\site-packages\cnocr\cn_ocr.py", line 155, in __init__
    self.rec_model = rec_cls(
  File "C:\Users\戴华乾\AppData\Local\Programs\Python\Python310\lib\site-packages\cnocr\ppocr\pp_recognizer.py", line 74, in __init__
    self._assert_and_prepare_model_files(model_fp, root)
  File "C:\Users\戴华乾\AppData\Local\Programs\Python\Python310\lib\site-packages\cnocr\ppocr\pp_recognizer.py", line 109, in _assert_and_prepare_model_files
    get_model_file(url, self._model_dir, download_source=DOWNLOAD_SOURCE)  # download the .zip file and unzip
  File "C:\Users\戴华乾\AppData\Local\Programs\Python\Python310\lib\site-packages\cnstd\utils\utils.py", line 257, in get_model_file
    with zipfile.ZipFile(zip_file_path) as zf:
  File "C:\Users\戴华乾\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\戴华乾\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by pumpkinjw** [comment]
用3.8看看

**Comment by a308086178** [comment]
> 用3.8看看

谢谢你的回复  我通过找到错误的来源是一个叫ONNXRuntime的文件已经损坏了 打不开 重新下载项目也不行 我会去尝试一下3.8版本py

**Comment by T-BAG1** [comment]
> > 用3.8看看
> 
> 谢谢你的回复 我通过找到错误的来源是一个叫ONNXRuntime的文件已经损坏了 打不开 重新下载项目也不行 我会去尝试一下3.8版本py

3.8版本可以运行吗
